#!/bin/bash

# Get the current volume value using pamixer
volume=$(pamixer --get-volume)

# Set icon based on volume value
if (( volume > 69 )); then
    icon="/usr/share/icons/BeautyLine/actions/scalable/audio-volume-high.svg"
elif (( volume > 35 )); then
    icon="/usr/share/icons/BeautyLine/actions/scalable/audio-volume-medium.svg"
else
    icon="/usr/share/icons/BeautyLine/actions/scalable/audio-volume-low.svg"
fi

# Send the notification
notify-send -u normal \
            "Volume : $volume%" \
            -i audio-volume-muted \
            -h int:value:$volume \
            -i "$icon" \
            -r 67544677
